# Samsung GPIO Debugging and Verification System
# Files relevant to each platform should be added at this MK file.

obj-$(CONFIG_ARCH_HAWAII)   += Hawaii_gpio_dvs.o
obj-$(CONFIG_ARCH_JAVA)   += Java_gpio_dvs.o