#
# Makefile for the Cypress touch driver
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_CYPRESS_TMA46X)  += cyttsp4_core.o	cyttsp4_i2c.o  cyttsp4_bus.o  cyttsp4_mtb.o  cyttsp4_mt_common.o cyttsp4_btn.o  cyttsp4_device_access.o cyttsp4_loader.o